version: '3'
services: 
  node_app:
    build:
      context: node
    container_name: node_app
    networks:
      - node-mysql-network
    ports:
      - "3000:3333"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    volumes: 
      - "./mysql:/docker-entrypoint-initdb.d"
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-mysql-network
networks:
  node-mysql-network:
    driver: bridge
