
version: '3'
services:

  db:
    build:
      context: db
    container_name: db  
    volumes: 
      - ./db/init:/docker-entrypoint-initdb.d
    restart: always
    tty: true   
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
   
  app:
    build:
      context: app
    container_name: app
    volumes:
      - ./app:/usr/src/app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s sh -c "npm install && node index"
    tty: true  
    depends_on:
      - db  

  nginx:
    build:
      context: nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - app