
version: '3'
services:
  db_app:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db_app  
    volumes: 
      - "./mysql:/docker-entrypoint-initdb.d"
    restart: always
    tty: true   
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
  node_app:
    build:
      context: node
    container_name: node_app
    entrypoint: dockerize -wait tcp://db_app:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - node-network   
    tty: true  
    depends_on:
      - db_app  
  nginx:
    build:
      context: nginx
    container_name: nginx_app
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - node_app 
networks:
  node-network:
    driver: bridge
    
    
    
    
